apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres.nyehvpubgddlksoppqvn:SuK014%40Supa@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true&connect_timeout=10"
  GMAIL_USER: "auming.itkit@gmail.com"
  GMAIL_PASSWORD: "ghua kypm safy lhxw"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55ZWh2cHViZ2RkbGtzb3BwcXZuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzU4MDg4MCwiZXhwIjoyMDczMTU2ODgwfQ.VjThpUqsnREdmj8SEvaD-OXiV7n3hGB1VBGi5GbQGY0"
